name: Deploy Ruby Sinatra App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH private key for accessing the server
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Add Server to Known Hosts
      run: |
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to Server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        ssh -i ~/.ssh/id_ed25519 $SERVER_USER@$SERVER_IP <<EOF
          set -e  # Exit immediately if a command fails

          # Navigate to the project directory
          cd /home/ubuntu/geo_track_1

          # Pull the latest changes from the repository
          git pull origin main

          # Ensure required Ruby gems are installed
          bundle install

          # Restart the systemd service
          sudo service puma restart

          # Wait a few seconds for the service to restart
          sleep 5
        EOF

    - name: Verify App Deployment
      run: |
        #curl --retry 5 --retry-delay 5 --connect-timeout 5 --max-time 30 http://${{ secrets.SERVER_IP }}/user_location
