name: Deploy Ruby Sinatra App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH private key for accessing the server
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Add Server to Known Hosts
      run: |
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to Server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        ssh -i ~/.ssh/id_ed25519 $SERVER_USER@$SERVER_IP <<EOF
          set -e  # Exit immediately if a command fails

          # Navigate to the project directory
          cd /home/ubuntu/geo_tracker
          
          # Pull the latest changes from the repository
          git pull origin main
          
          # Stop any running app process
          pkill -f 'ruby' || true

          # Ensure required Ruby gems are installed
          bundle install

          # Start the app using the ruby command
          nohup ruby app.rb -o 0.0.0.0 -p 4567 > ruby_app.log 2>&1 &
          
          # Wait a few seconds for the server to start
          sleep 5
        EOF

    - name: Verify App Deployment
      run: |
        curl --retry 5 --retry-delay 5 --max-time 11 http://${{ secrets.SERVER_IP }}:4567/user_location
