name: Deploy Ruby Sinatra App

on:
  push:
    branches:
      - main  # Trigger deployment on commits to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH private key for accessing the server
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Add Server to Known Hosts
      run: |
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to Server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        ssh -i ~/.ssh/id_ed25519 $SERVER_USER@$SERVER_IP << 'EOF'
          cd /home/ubuntu/project/geo_tracker
          git pull origin main  # Pull the latest code from the main branch
          pkill -f 'ruby.*app.rb' || true  # Stop any running Ruby process for app.rb
          ruby app.rb -o 0.0.0.0 -p 4567 & # Start the Sinatra application
          # Wait for the Sinatra app to be ready, by checking the public IP
          curl --retry 10 --retry-delay 5 --max-time 60 http://54.160.215.88:4567
         EOF

